Spring Boot Tests
deykunx/book-store pull request #11
Opened 2023-09-07 12:00 UTC by deykunx

2023-09-07 12:01 UTC, deykunx commented
![image](https://github.com/deykunx/book-store/assets/119003767/190681a2-4c56-4941-9464-7fcda9437f33)

2023-09-07 17:24 UTC, aaananas requested changes

2023-09-07 17:24 UTC, aaananas commented on src/test/java/com/bookstore/controller/BookControllerTest.java
> +        when(bookService.findAll(any(Pageable.class))).thenReturn(expected);
controller tests should be integrational))

2023-09-07 17:24 UTC, aaananas commented on src/test/java/com/bookstore/controller/BookControllerTest.java
> +                        .content(new ObjectMapper().writeValueAsString(requestDto)))
```suggestion
                        .content(objectMapper.writeValueAsString(requestDto)))
```

2023-09-12 17:30 UTC, deykunx commented
![image](https://github.com/deykunx/book-store/assets/119003767/f969739f-64b9-46fa-b4d1-ba45c87c2abc)

2023-09-13 11:59 UTC, merged