1. created BookDto, BookController, updated BookRepository and BookSe…
deykunx/book-store pull request #2
Opened 2023-08-17 16:24 UTC by deykunx

…rvice, added new Exception and Mapper

2023-08-17 17:19 UTC, aaananas requested changes

2023-08-17 17:19 UTC, aaananas commented on src/main/java/com/bookstore/controller/BookController.java
> +        return bookService.findById(id);
remember about access modifier

2023-08-17 17:19 UTC, aaananas commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(book);
```suggestion
        return bookRepository.findById(id)
                                .map(book -> bookMapper.toDto(book))
                                .orElseThrow(
                () -> new EntityNotFoundException("Can't find book by id: " + id));
```

just a suggestion, not a mistake

2023-08-18 10:04 UTC, Rommelua approved these changes

2023-08-18 10:04 UTC, Rommelua commented on src/main/java/com/bookstore/model/Book.java
>  @Data
do not use @Data in entities

2023-08-18 12:31 UTC, merged